apiVersion: v1
kind: Service
metadata:
  name: devops-sample-app-svc
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: devops-sample-app